apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: heart-ui
  template:
    metadata:
      labels:
        app: heart-ui
    spec:
      containers:
      - name: heart-ui
        image: keshavx/heart-ui:latest  # Replace with your actual image
        ports:
        - containerPort: 8501
        env:
        - name: FASTAPI_URL
          value: "http://heart-api-service"

